### ISSUE TITLE
Tests failures with Sphinx 1.3

### ISSUE THREAD

**Issue by mitya57** [lunaryorn/sphinxcontrib-programoutput#3]
When running tests with Sphinx 1.3, I get some errors. See https://gist.github.com/mitya57/1643a7c1666b650a0de5.

It will be nice to have a new version compatible with both 1.2 and 1.3.

**Comment by lunaryorn** [comment]
@mitya57 Pull request welcome.  I have no longer any use for this extension, and I'm not really maintaining this anymore.

**Comment by mitya57** [comment]
OK, maybe will do later.
